# Generated by Django 3.1.1 on 2020-09-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('deadline', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField()),
                ('tags', models.ManyToManyField(to='tasks.Tag')),
            ],
        ),
    ]
